### ISSUE TITLE
数据文件提供

### ISSUE THREAD

**Issue by freeyangHaha** [LDLINGLINGLING/AutoPlan#2]
在main.py中看到了‘/ai/ld/remote/Qwen-main/get_subtask/data_process/all_data.txt'这个路径文件，作者能否提供一下

**Comment by LDLINGLINGLING** [comment]
请给邮箱

**Comment by SC19072** [comment]
ustcxydu@mail.ustc.edu.cn

**Comment by SC19072** [comment]
> 请给邮箱
https://github.com/LDLINGLINGLING/AutoPlan/issues/2#issuecomment-2066023530

**Comment by freeyangHaha** [comment]
ustcxydu@mail.ustc.edu.cn

**Comment by wuhuoogui** [comment]
作者您好，同需要‘/ai/ld/remote/Qwen-main/get_subtask/data_process/all_data.txt'这个数据文件，邮箱：22332114@zju.edu.cn

**Comment by JustWeZero** [comment]
@SC19072 你好，我也需要该数据集文件，麻烦发送一下谢谢。邮箱：zf1906242@buaa.edu.cn

**Comment by LDLINGLINGLING** [comment]
已上传
