### ISSUE TITLE
关于数据集训练问题

### ISSUE THREAD

**Issue by Awacky** [LDLINGLINGLING/AutoPlan#4]
你好，就是这个train_react.json这个数据集是不是还要调整格式？我想采用LLMA-factory框架微调一下，数据集的格式总是不是很对

**Comment by LDLINGLINGLING** [comment]
这个是原来qwen的chatml格式，llamafactory不知道支持步

**Comment by Awacky** [comment]
中间有一个target_and_mapdict函数，我好像没在数据集里面看到过
